import heroCity from "@/assets/hero-city.jpg";
import techAi from "@/assets/tech-ai.jpg";
import scienceBattery from "@/assets/science-battery.jpg";
import type { Article, Edition, EditionSummary, Feed, Settings } from "./types";

const todayIso = "2025-05-20";

export const MOCK_ARTICLES: Article[] = [
  {
    id: "a1",
    slug: "global-cities-race-climate",
    category: "world",
    eyebrow: "TOP STORY",
    headline: "Global cities race to adapt to a changing climate",
    deck: "From flood defenses to green infrastructure, mayors say urgent action today will determine the livability of tomorrow.",
    summary:
      "City leaders from more than 40 countries gathered in Singapore this week for the Global Resilient Cities Summit, sharing strategies to tackle climate threats ranging from extreme heat to rising seas. Funding, innovation, and cross-border collaboration took center stage as mayors emphasized that adaptation is no longer optional.",
    whyItMatters:
      "Two thirds of the world will live in urban areas by 2050. The decisions made by city halls this decade will determine where billions of people can safely live and work.",
    keyPoints: [
      "40+ cities pledged shared flood-defense funding by 2030.",
      "Singapore unveiled a $4B coastal protection program.",
      "New cross-city data-sharing platform launches in Q3.",
    ],
    source: { name: "Associated Press", url: "https://apnews.com", reliability: "high" },
    author: "Olivia Grant",
    originalUrl: "https://apnews.com/example",
    publishedAt: "2025-05-20T04:10:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 6,
    relevanceScore: 0.97,
    confidenceScore: 0.92,
    image: {
      url: heroCity,
      attribution: "AP Images",
      caption:
        "Singapore is investing in coastal defenses and sustainable urban planning to prepare for rising seas.",
    },
    tags: ["climate", "cities", "policy"],
    relatedIds: ["a4", "a5"],
  },
  {
    id: "a2",
    slug: "european-defense-strategy",
    category: "world",
    headline: "European leaders push for unified defense strategy",
    summary:
      "EU leaders met in Brussels to advance a joint defense initiative aimed at strengthening capabilities and reducing dependence on external allies.",
    keyPoints: [
      "€80B joint procurement framework discussed.",
      "Eastern members pushed for a faster timeline.",
    ],
    source: { name: "DW", url: "https://www.dw.com", reliability: "high" },
    author: "Claire Donovan",
    originalUrl: "https://www.dw.com/example",
    publishedAt: "2025-05-20T03:15:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.88,
    confidenceScore: 0.9,
    tags: ["europe", "defense"],
    relatedIds: [],
  },
  {
    id: "a3",
    slug: "markets-rise-inflation-cools",
    category: "business",
    headline: "Markets rise as inflation cools in key regions",
    summary:
      "Global markets opened higher after new data showed inflation easing in the U.S. and Europe, boosting investor confidence.",
    keyPoints: [
      "U.S. CPI fell to 2.4% year-over-year.",
      "Euro area core inflation at 18-month low.",
    ],
    source: { name: "Reuters", url: "https://reuters.com", reliability: "high" },
    author: "Marcus Lee",
    originalUrl: "https://reuters.com/example",
    publishedAt: "2025-05-20T02:45:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 3,
    relevanceScore: 0.82,
    confidenceScore: 0.91,
    tags: ["markets", "inflation"],
    relatedIds: [],
  },
  {
    id: "a4",
    slug: "ai-regulation-frameworks",
    category: "technology",
    headline: "AI regulation frameworks take shape worldwide",
    summary:
      "New policies in the EU and Asia aim to balance innovation with transparency and safety as generative AI tools become more powerful.",
    keyPoints: [
      "EU AI Act enforcement begins next quarter.",
      "Japan publishes voluntary safety standard.",
      "U.S. agencies adopt model evaluation guidelines.",
    ],
    source: { name: "The Verge", url: "https://theverge.com", reliability: "high" },
    author: "Daniel Chen",
    originalUrl: "https://theverge.com/example",
    publishedAt: "2025-05-20T01:30:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 5,
    relevanceScore: 0.86,
    confidenceScore: 0.89,
    image: { url: techAi, attribution: "Reuters", caption: "AI chip on circuit board." },
    tags: ["ai", "policy", "regulation"],
    relatedIds: ["a1"],
  },
  {
    id: "a5",
    slug: "battery-tech-breakthrough",
    category: "science",
    headline: "Breakthrough in battery tech could power the next generation",
    summary:
      "Researchers develop a solid-state battery with higher capacity and faster charging, bringing long-range EV vehicles closer to reality.",
    keyPoints: [
      "Energy density 40% higher than current Li-ion.",
      "Charging from 10% to 80% in under 12 minutes.",
      "Commercial production targeted for 2027.",
    ],
    source: { name: "Nature", url: "https://nature.com", reliability: "high" },
    author: "Maya Patel",
    originalUrl: "https://nature.com/example",
    publishedAt: "2025-05-20T00:50:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 6,
    relevanceScore: 0.84,
    confidenceScore: 0.93,
    image: {
      url: scienceBattery,
      attribution: "Nature",
      caption: "Solid-state battery prototypes.",
    },
    tags: ["energy", "ev", "research"],
    relatedIds: ["a1"],
  },
  {
    id: "a6",
    slug: "ceasefire-talks-resume",
    category: "world",
    headline: "Ceasefire talks resume in the Middle East with cautious optimism",
    summary:
      "Mediators report incremental progress as parties return to the negotiating table after a month-long pause.",
    keyPoints: ["Humanitarian corridors discussed.", "Phased exchange proposed."],
    source: { name: "Al Jazeera", url: "https://aljazeera.com", reliability: "high" },
    originalUrl: "https://aljazeera.com/example",
    publishedAt: "2025-05-20T01:55:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.78,
    confidenceScore: 0.84,
    tags: ["geopolitics"],
    relatedIds: [],
  },
  {
    id: "a7",
    slug: "oil-prices-dip",
    category: "business",
    headline: "Oil prices dip on demand concerns as China's growth outlook softens",
    summary:
      "Brent crude slid as new industrial output data raised questions about second-half consumption.",
    keyPoints: ["Brent down 0.85% on the day.", "OPEC+ meeting next week."],
    source: { name: "Financial Times", url: "https://ft.com", reliability: "high" },
    originalUrl: "https://ft.com/example",
    publishedAt: "2025-05-20T02:05:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 3,
    relevanceScore: 0.75,
    confidenceScore: 0.88,
    tags: ["oil", "china"],
    relatedIds: [],
  },
  {
    id: "a8",
    slug: "alzheimers-early-screening",
    category: "science",
    headline: "New study highlights the benefits of early screening for Alzheimer's disease",
    summary:
      "Early detection improved long-term outcomes in a multi-country cohort, researchers report.",
    keyPoints: ["Cohort of 12,000 across 8 countries.", "Five-year improvement signal."],
    source: { name: "The Guardian", url: "https://theguardian.com", reliability: "high" },
    originalUrl: "https://theguardian.com/example",
    publishedAt: "2025-05-20T02:20:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.74,
    confidenceScore: 0.86,
    tags: ["health", "research"],
    relatedIds: [],
  },
  {
    id: "a9",
    slug: "venice-biennale-opens",
    category: "culture",
    headline: "Venice Biennale opens with focus on memory and migration",
    summary: "This year's curation centers on artists exploring identity across shifting borders.",
    keyPoints: ["89 national pavilions.", "Themes of memory, displacement, and home."],
    source: { name: "ARTnews", url: "https://artnews.com", reliability: "high" },
    originalUrl: "https://artnews.com/example",
    publishedAt: "2025-05-19T22:10:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 5,
    relevanceScore: 0.7,
    confidenceScore: 0.82,
    tags: ["art", "culture"],
    relatedIds: [],
  },
  {
    id: "a10",
    slug: "pacific-trade-pact",
    category: "world",
    headline: "Pacific nations sign expanded trade pact after years of stalled talks",
    summary:
      "Twelve economies finalized tariff reductions on digital goods and agricultural exports, signaling a pivot toward regional integration.",
    keyPoints: [
      "Tariffs cut on 1,400 product lines.",
      "Digital-services chapter is the first of its kind.",
    ],
    source: { name: "Reuters", url: "https://reuters.com", reliability: "high" },
    author: "Hana Sato",
    originalUrl: "https://reuters.com/example-trade",
    publishedAt: "2025-05-20T03:40:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.81,
    confidenceScore: 0.88,
    tags: ["trade", "asia-pacific"],
    relatedIds: [],
  },
  {
    id: "a11",
    slug: "chip-export-controls",
    category: "technology",
    headline: "Chip export controls tighten as supply chains reroute through Southeast Asia",
    summary:
      "New licensing rules from Washington and Brussels are pushing fabricators to diversify packaging and assembly outside their traditional hubs.",
    keyPoints: [
      "Vietnam and Malaysia gain new fab investment.",
      "License approvals slow to 90+ days.",
    ],
    source: { name: "Bloomberg", url: "https://bloomberg.com", reliability: "high" },
    author: "Priya Raman",
    originalUrl: "https://bloomberg.com/example-chips",
    publishedAt: "2025-05-20T02:55:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 5,
    relevanceScore: 0.83,
    confidenceScore: 0.87,
    tags: ["semiconductors", "trade", "supply-chain"],
    relatedIds: ["a4"],
  },
  {
    id: "a12",
    slug: "open-source-model-release",
    category: "technology",
    headline: "A new open-weights model challenges closed labs on reasoning benchmarks",
    summary:
      "A consortium released a 70B-parameter model with permissive licensing that matches leading proprietary systems on math and code tasks.",
    keyPoints: ["Apache-2.0 license.", "Tops three public reasoning benchmarks."],
    source: { name: "Ars Technica", url: "https://arstechnica.com", reliability: "high" },
    originalUrl: "https://arstechnica.com/example-model",
    publishedAt: "2025-05-20T01:05:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.79,
    confidenceScore: 0.86,
    tags: ["ai", "open-source"],
    relatedIds: ["a4"],
  },
  {
    id: "a13",
    slug: "central-banks-divergence",
    category: "business",
    headline: "Central banks diverge as growth and inflation pictures split",
    summary:
      "The ECB signaled a summer cut while the Fed held firm, widening the policy gap and rippling through currency markets.",
    keyPoints: ["EUR/USD slid to a six-week low.", "Bond traders price two cuts by year-end."],
    source: { name: "Wall Street Journal", url: "https://wsj.com", reliability: "high" },
    author: "Theo Bauer",
    originalUrl: "https://wsj.com/example-rates",
    publishedAt: "2025-05-20T03:00:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.8,
    confidenceScore: 0.9,
    tags: ["rates", "fx"],
    relatedIds: ["a3"],
  },
  {
    id: "a14",
    slug: "retail-earnings-mixed",
    category: "business",
    headline: "Retail earnings split the market as consumers trade down",
    summary:
      "Discount chains beat expectations while mid-tier department stores warned on margins, sharpening the K-shaped consumer story.",
    keyPoints: ["Discounter comps up 6.4%.", "Two majors cut full-year guidance."],
    source: { name: "CNBC", url: "https://cnbc.com", reliability: "high" },
    originalUrl: "https://cnbc.com/example-retail",
    publishedAt: "2025-05-20T02:25:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 3,
    relevanceScore: 0.74,
    confidenceScore: 0.85,
    tags: ["retail", "consumer"],
    relatedIds: [],
  },
  {
    id: "a15",
    slug: "exoplanet-atmosphere",
    category: "science",
    headline: "Telescope detects water vapor in atmosphere of a temperate exoplanet",
    summary:
      "Spectral readings from a planet 41 light-years away reveal conditions astronomers say warrant deeper follow-up campaigns.",
    keyPoints: ["Planet sits in the habitable zone.", "Follow-up time approved for 2026."],
    source: { name: "NASA", url: "https://nasa.gov", reliability: "high" },
    author: "Lin Wei",
    originalUrl: "https://nasa.gov/example-exo",
    publishedAt: "2025-05-20T00:20:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 5,
    relevanceScore: 0.77,
    confidenceScore: 0.88,
    tags: ["astronomy", "exoplanets"],
    relatedIds: [],
  },
  {
    id: "a16",
    slug: "fusion-milestone",
    category: "science",
    headline: "Private fusion startup reports sustained plasma at record duration",
    summary:
      "The 22-minute run clears a key engineering hurdle, though commercial power remains years away, independent reviewers say.",
    keyPoints: ["22-minute plasma confinement.", "Independent review pending."],
    source: {
      name: "MIT Technology Review",
      url: "https://technologyreview.com",
      reliability: "high",
    },
    originalUrl: "https://technologyreview.com/example-fusion",
    publishedAt: "2025-05-19T23:40:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 5,
    relevanceScore: 0.76,
    confidenceScore: 0.84,
    tags: ["energy", "fusion"],
    relatedIds: ["a5"],
  },
  {
    id: "a17",
    slug: "literary-prize-shortlist",
    category: "culture",
    headline: "International literary prize shortlist spans five continents",
    summary:
      "Judges praised a slate that foregrounds translation and debut novelists, with a record number of small-press titles in contention.",
    keyPoints: ["Six novels, five languages.", "Three debut authors shortlisted."],
    source: { name: "The Guardian", url: "https://theguardian.com", reliability: "high" },
    originalUrl: "https://theguardian.com/example-books",
    publishedAt: "2025-05-19T21:30:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.68,
    confidenceScore: 0.83,
    tags: ["literature", "prize"],
    relatedIds: [],
  },
  {
    id: "a18",
    slug: "film-festival-lineup",
    category: "culture",
    headline: "Cannes lineup leans into hybrid documentary and emerging directors",
    summary:
      "Festival programmers say the slate reflects a generational shift toward genre-blurring nonfiction.",
    keyPoints: ["21 films in competition.", "Seven first-time directors."],
    source: { name: "Variety", url: "https://variety.com", reliability: "high" },
    originalUrl: "https://variety.com/example-cannes",
    publishedAt: "2025-05-19T20:00:00Z",
    retrievedAt: "2025-05-20T05:25:00Z",
    readingTimeMin: 4,
    relevanceScore: 0.66,
    confidenceScore: 0.82,
    tags: ["film", "festivals"],
    relatedIds: [],
  },
];

export const MOCK_EDITION: Edition = {
  id: "ed-2025-05-20",
  editionDate: todayIso,
  status: "published",
  generatedAt: "2025-05-20T05:28:00Z",
  publishedAt: "2025-05-20T05:30:00Z",
  updatedByAiAt: "2025-05-20T05:30:00Z",
  nextScheduledAt: "2025-05-21T05:30:00Z",
  sourceCount: 42,
  storiesAnalyzed: 318,
  readingTimeMin: 12,
  leadArticleId: "a1",
  articles: MOCK_ARTICLES,
  morningBriefing: [
    {
      topic: "Geopolitics",
      text: "Ceasefire talks resume in the Middle East with cautious optimism.",
      sourceName: "Al Jazeera",
      articleId: "a6",
      icon: "globe",
    },
    {
      topic: "Economy",
      text: "Oil prices dip on demand concerns as China's growth outlook softens.",
      sourceName: "Financial Times",
      articleId: "a7",
      icon: "chart",
    },
    {
      topic: "Health",
      text: "New study highlights the benefits of early screening for Alzheimer's disease.",
      sourceName: "The Guardian",
      articleId: "a8",
      icon: "health",
    },
  ],
  editorsNote: {
    text: "Today's top stories highlight how cities, policies, and technologies are shaping our future in the face of climate, economic, and technological change.",
    whyItMatters:
      "Climate adaptation, smart regulation, and clean energy breakthroughs dominate the global agenda — each with long-term impact on communities and economies.",
    model: "lovable-ai/gemini-3-flash",
    generatedAt: "2025-05-20T05:29:00Z",
    sourcesConsidered: 42,
  },
  markets: [
    { symbol: "S&P 500", value: "5,312.07", changePct: 1.02 },
    { symbol: "FTSE 100", value: "8,726.71", changePct: 0.68 },
    { symbol: "DAX", value: "18,772.85", changePct: 0.74 },
    { symbol: "NIKKEI 225", value: "38,529.48", changePct: 1.1 },
  ],
  commodities: [
    { symbol: "Brent Oil", value: "$64.12", changePct: -0.85 },
    { symbol: "Gold", value: "$2,415.60", changePct: 0.35 },
    { symbol: "10Y BOND (US)", value: "4.42%", changePct: -0.03 },
  ],
  weather: [
    { city: "New York", tempC: 22, condition: "Partly Cloudy", icon: "partly" },
    { city: "London", tempC: 16, condition: "Mostly Cloudy", icon: "cloud" },
    { city: "Paris", tempC: 17, condition: "Partly Cloudy", icon: "partly" },
    { city: "Berlin", tempC: 18, condition: "Showers", icon: "rain" },
    { city: "Tokyo", tempC: 24, condition: "Sunny", icon: "sun" },
    { city: "Sydney", tempC: 20, condition: "Partly Cloudy", icon: "partly" },
  ],
  sections: [
    {
      id: "world",
      label: "World",
      eyebrow: "The World Desk",
      dek: "Geopolitics, diplomacy, and the stories shaping nations before sunrise.",
      order: 1,
      visible: true,
      articleIds: ["a2", "a6", "a10"],
    },
    {
      id: "technology",
      label: "Technology",
      eyebrow: "The Technology Desk",
      dek: "Models, chips, platforms, and the policy lines being drawn around them.",
      order: 2,
      visible: true,
      articleIds: ["a4", "a11", "a12"],
    },
    {
      id: "business",
      label: "Business",
      eyebrow: "Markets & Business",
      dek: "Macro signals, central banks, earnings, and the deals moving capital today.",
      order: 3,
      visible: true,
      articleIds: ["a3", "a7", "a13", "a14"],
    },
    {
      id: "science",
      label: "Science",
      eyebrow: "Science & Research",
      dek: "Breakthroughs from labs, observatories, and clinical trials worth your attention.",
      order: 4,
      visible: true,
      articleIds: ["a5", "a8", "a15", "a16"],
    },
    {
      id: "culture",
      label: "Culture",
      eyebrow: "Culture & Ideas",
      dek: "Art, books, film, and the conversations defining the week.",
      order: 5,
      visible: true,
      articleIds: ["a9", "a17", "a18"],
    },
  ],
};

export const MOCK_EDITION_SUMMARIES: EditionSummary[] = [
  {
    id: "ed-2025-05-20",
    editionDate: "2025-05-20",
    status: "published",
    storyCount: 9,
    leadHeadline: "Global cities race to adapt to a changing climate",
    categories: ["world", "business", "technology", "science", "culture"],
  },
  {
    id: "ed-2025-05-19",
    editionDate: "2025-05-19",
    status: "published",
    storyCount: 8,
    leadHeadline: "Renewables overtake coal in three more economies",
    categories: ["world", "business", "science"],
  },
  {
    id: "ed-2025-05-18",
    editionDate: "2025-05-18",
    status: "published_with_warnings",
    storyCount: 7,
    leadHeadline: "Quiet diplomacy reshapes Pacific trade map",
    categories: ["world", "business"],
  },
  {
    id: "ed-2025-05-17",
    editionDate: "2025-05-17",
    status: "published",
    storyCount: 10,
    leadHeadline: "Megacity transit shifts toward shared electric fleets",
    categories: ["world", "technology", "business", "culture"],
  },
];

export const MOCK_FEEDS: Feed[] = [
  {
    id: "f1",
    name: "Reuters Top News",
    url: "https://feeds.reuters.com/reuters/topNews",
    category: "world",
    enabled: true,
    lastSuccessAt: "2025-05-20T05:22:00Z",
    health: "healthy",
  },
  {
    id: "f2",
    name: "Associated Press",
    url: "https://apnews.com/rss",
    category: "world",
    enabled: true,
    lastSuccessAt: "2025-05-20T05:21:00Z",
    health: "healthy",
  },
  {
    id: "f3",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    category: "technology",
    enabled: true,
    lastSuccessAt: "2025-05-20T05:18:00Z",
    health: "healthy",
  },
  {
    id: "f4",
    name: "Financial Times",
    url: "https://www.ft.com/rss/home",
    category: "business",
    enabled: true,
    lastSuccessAt: "2025-05-20T05:19:00Z",
    health: "healthy",
  },
  {
    id: "f5",
    name: "Nature News",
    url: "https://www.nature.com/nature.rss",
    category: "science",
    enabled: true,
    lastSuccessAt: "2025-05-20T05:15:00Z",
    health: "degraded",
    lastError: "Slow response (4.2s)",
  },
  {
    id: "f6",
    name: "ARTnews",
    url: "https://artnews.com/feed",
    category: "culture",
    enabled: false,
    health: "down",
    lastError: "404 since 2025-05-18",
  },
];

export const MOCK_SETTINGS: Settings = {
  personalization: {
    preferredCategories: ["world", "technology", "business", "science"],
    mutedTopics: ["celebrity"],
    preferredSources: ["Reuters", "AP", "Nature", "The Guardian"],
    blockedSources: [],
    geographicInterests: ["United States", "Europe", "Japan"],
    keywordInterests: ["climate", "AI policy", "energy"],
    viewpointDiversity: "balanced",
    maxStoriesPerEdition: 9,
  },
  schedule: {
    deliveryTime: "05:30",
    timezone: "Europe/Berlin",
    days: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    autoGenerate: true,
    regenerateOnFailure: true,
  },
  ai: {
    providerConfigured: true,
    provider: "Lovable AI Gateway",
    model: "google/gemini-3-flash-preview",
    summaryLength: "medium",
    tone: "analytical",
    includeWhyItMatters: true,
    includeCrossStoryAnalysis: true,
    sourceBalancing: true,
  },
  feeds: MOCK_FEEDS,
};
