import type { NewspaperEdition } from "@/lib/schema";

export const minimalValidEdition: NewspaperEdition = {
  schemaVersion: "1.0.0",
  editionId: "ed-2025-05-20-test",
  editionDate: "2025-05-20",
  editionNumber: 1,
  status: "published",
  generatedAt: "2025-05-20T05:00:00Z",
  publishedAt: "2025-05-20T05:30:00Z",
  updatedAt: "2025-05-20T05:30:00Z",
  timezone: "UTC",
  locale: "en-US",
  masthead: {
    title: "The Test Wire",
    tagline: "Test Edition",
  },
  utilityBar: {
    dateLabel: "May 20, 2025",
    weather: { tempC: 20, condition: "Sunny", icon: "sun" },
    editionLabel: "Test",
    updatedByAiAt: "05:30",
    nextEditionText: "Next edition soon",
  },
  navigation: {
    items: [
      { id: "top", label: "Top Stories", path: "/" },
      { id: "world", label: "World", path: "/world", category: "world" },
    ],
    moreLinks: [{ id: "saved", label: "Saved", path: "/saved" }],
  },
  leadStoryId: "lead-1",
  articles: [
    {
      id: "lead-1",
      slug: "lead-story",
      displayPosition: "lead",
      headline: "Lead story headline",
      summary: "Lead story summary that is safe plain text.",
      content: "Lead story summary that is safe plain text.",
      category: "world",
      tags: ["tag-one"],
      source: { name: "Test Source", url: "https://apnews.com", reliability: "high" },
      originalUrl: "https://apnews.com/lead",
      publishedAt: "2025-05-20T04:00:00Z",
      retrievedAt: "2025-05-20T05:00:00Z",
      readingTimeMin: 3,
      keyPoints: ["First point."],
      relatedArticleIds: [],
      relevanceScore: 0.9,
      confidenceScore: 0.9,
      editorialProminence: 1.0,
      aiDisclosure: { summaryIsAiGenerated: true, model: "test-model" },
    },
    {
      id: "sidebar-1",
      slug: "sidebar-story",
      displayPosition: "sidebar",
      headline: "Sidebar story headline",
      summary: "Sidebar story summary.",
      content: "Sidebar story summary.",
      category: "business",
      tags: ["markets"],
      source: { name: "Reuters", url: "https://reuters.com", reliability: "high" },
      originalUrl: "https://reuters.com/sidebar",
      publishedAt: "2025-05-20T04:00:00Z",
      retrievedAt: "2025-05-20T05:00:00Z",
      readingTimeMin: 2,
      keyPoints: ["Sidebar point."],
      relatedArticleIds: [],
      relevanceScore: 0.7,
      confidenceScore: 0.8,
      editorialProminence: 0.6,
      aiDisclosure: { summaryIsAiGenerated: true },
    },
    {
      id: "feature-1",
      slug: "feature-story",
      displayPosition: "imageFeature",
      headline: "Feature story headline",
      summary: "Feature story summary.",
      content: "Feature story summary.",
      category: "technology",
      tags: ["ai"],
      source: { name: "The Verge", url: "https://theverge.com", reliability: "high" },
      originalUrl: "https://theverge.com/feature",
      publishedAt: "2025-05-20T04:00:00Z",
      retrievedAt: "2025-05-20T05:00:00Z",
      readingTimeMin: 4,
      image: { url: "/images/feature.jpg", alt: "Feature image" },
      keyPoints: ["Feature point."],
      relatedArticleIds: ["lead-1"],
      relevanceScore: 0.8,
      confidenceScore: 0.85,
      editorialProminence: 0.75,
      aiDisclosure: { summaryIsAiGenerated: true },
    },
  ],
  sections: [
    {
      id: "world",
      label: "World",
      eyebrow: "World Desk",
      dek: "World news.",
      order: 1,
      visible: true,
      articleIds: ["lead-1"],
    },
    {
      id: "business",
      label: "Business",
      eyebrow: "Business Desk",
      dek: "Business news.",
      order: 2,
      visible: true,
      articleIds: ["sidebar-1"],
    },
  ],
  morningBriefing: [
    {
      topic: "Top line",
      text: "Briefing text.",
      sourceName: "Test Source",
      articleId: "lead-1",
      icon: "globe",
    },
  ],
  editorsNote: {
    text: "Editor note text.",
    whyItMatters: "Why it matters text.",
    model: "test-model",
    generatedAt: "2025-05-20T05:10:00Z",
    sourcesConsidered: 5,
  },
  marketSnapshot: {
    updatedAt: "2025-05-20T05:15:00Z",
    sourceName: "Bloomberg",
    sourceUrl: "https://bloomberg.com",
    tickers: [{ symbol: "S&P 500", value: "5,000", changePct: 1.0 }],
    commodities: [{ symbol: "Oil", value: "$70", changePct: -0.5 }],
  },
  weather: {
    sourceName: "AccuWeather",
    sourceUrl: "https://accuweather.com",
    cities: [{ city: "New York", tempC: 22, condition: "Partly Cloudy", icon: "partly" }],
  },
  sources: [{ name: "Test Source", url: "https://apnews.com", articles: 1 }],
  generationMetadata: {
    model: "test-model",
    sourcesCount: 1,
    storiesAnalyzed: 5,
    readingTimeMin: 3,
  },
  footer: {
    copyright: "© 2025 Test Wire",
    links: [{ label: "Privacy", path: "/settings" }],
  },
};
