/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as WarRouteImport } from './routes/war'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PretextDemoRouteImport } from './routes/pretext-demo'
import { Route as PoliticsRouteImport } from './routes/politics'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionCategoryRouteImport } from './routes/section.$category'
import { Route as EditionsDateRouteImport } from './routes/editions.$date'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiSavedRouteImport } from './routes/api/saved'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiEditionsRouteImport } from './routes/api/editions'
import { Route as ApiCryptoTickerRouteImport } from './routes/api/crypto-ticker'
import { Route as ApiEditionsDateRouteImport } from './routes/api/editions/$date'
import { Route as ApiEditionLatestRouteImport } from './routes/api/edition/latest'
import { Route as ApiArticlesIdRouteImport } from './routes/api/articles/$id'
import { Route as ApiAdminRollbackRouteImport } from './routes/api/admin/rollback'
import { Route as ApiAdminGenerateRouteImport } from './routes/api/admin/generate'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const WarRoute = WarRouteImport.update({
  id: '/war',
  path: '/war',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PretextDemoRoute = PretextDemoRouteImport.update({
  id: '/pretext-demo',
  path: '/pretext-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticsRoute = PoliticsRouteImport.update({
  id: '/politics',
  path: '/politics',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionCategoryRoute = SectionCategoryRouteImport.update({
  id: '/section/$category',
  path: '/section/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsDateRoute = EditionsDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => EditionsRoute,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavedRoute = ApiSavedRouteImport.update({
  id: '/api/saved',
  path: '/api/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditionsRoute = ApiEditionsRouteImport.update({
  id: '/api/editions',
  path: '/api/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCryptoTickerRoute = ApiCryptoTickerRouteImport.update({
  id: '/api/crypto-ticker',
  path: '/api/crypto-ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditionsDateRoute = ApiEditionsDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => ApiEditionsRoute,
} as any)
const ApiEditionLatestRoute = ApiEditionLatestRouteImport.update({
  id: '/api/edition/latest',
  path: '/api/edition/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArticlesIdRoute = ApiArticlesIdRouteImport.update({
  id: '/api/articles/$id',
  path: '/api/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRollbackRoute = ApiAdminRollbackRouteImport.update({
  id: '/api/admin/rollback',
  path: '/api/admin/rollback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGenerateRoute = ApiAdminGenerateRouteImport.update({
  id: '/api/admin/generate',
  path: '/api/admin/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/crypto': typeof CryptoRoute
  '/culture': typeof CultureRoute
  '/editions': typeof EditionsRouteWithChildren
  '/politics': typeof PoliticsRoute
  '/pretext-demo': typeof PretextDemoRoute
  '/saved': typeof SavedRoute
  '/science': typeof ScienceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/technology': typeof TechnologyRoute
  '/war': typeof WarRoute
  '/world': typeof WorldRoute
  '/api/crypto-ticker': typeof ApiCryptoTickerRoute
  '/api/editions': typeof ApiEditionsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/saved': typeof ApiSavedRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editions/$date': typeof EditionsDateRoute
  '/section/$category': typeof SectionCategoryRoute
  '/api/admin/generate': typeof ApiAdminGenerateRoute
  '/api/admin/rollback': typeof ApiAdminRollbackRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/edition/latest': typeof ApiEditionLatestRoute
  '/api/editions/$date': typeof ApiEditionsDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/crypto': typeof CryptoRoute
  '/culture': typeof CultureRoute
  '/editions': typeof EditionsRouteWithChildren
  '/politics': typeof PoliticsRoute
  '/pretext-demo': typeof PretextDemoRoute
  '/saved': typeof SavedRoute
  '/science': typeof ScienceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/technology': typeof TechnologyRoute
  '/war': typeof WarRoute
  '/world': typeof WorldRoute
  '/api/crypto-ticker': typeof ApiCryptoTickerRoute
  '/api/editions': typeof ApiEditionsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/saved': typeof ApiSavedRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editions/$date': typeof EditionsDateRoute
  '/section/$category': typeof SectionCategoryRoute
  '/api/admin/generate': typeof ApiAdminGenerateRoute
  '/api/admin/rollback': typeof ApiAdminRollbackRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/edition/latest': typeof ApiEditionLatestRoute
  '/api/editions/$date': typeof ApiEditionsDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/crypto': typeof CryptoRoute
  '/culture': typeof CultureRoute
  '/editions': typeof EditionsRouteWithChildren
  '/politics': typeof PoliticsRoute
  '/pretext-demo': typeof PretextDemoRoute
  '/saved': typeof SavedRoute
  '/science': typeof ScienceRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/technology': typeof TechnologyRoute
  '/war': typeof WarRoute
  '/world': typeof WorldRoute
  '/api/crypto-ticker': typeof ApiCryptoTickerRoute
  '/api/editions': typeof ApiEditionsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/saved': typeof ApiSavedRoute
  '/api/search': typeof ApiSearchRoute
  '/api/settings': typeof ApiSettingsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/editions/$date': typeof EditionsDateRoute
  '/section/$category': typeof SectionCategoryRoute
  '/api/admin/generate': typeof ApiAdminGenerateRoute
  '/api/admin/rollback': typeof ApiAdminRollbackRoute
  '/api/articles/$id': typeof ApiArticlesIdRoute
  '/api/edition/latest': typeof ApiEditionLatestRoute
  '/api/editions/$date': typeof ApiEditionsDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/crypto'
    | '/culture'
    | '/editions'
    | '/politics'
    | '/pretext-demo'
    | '/saved'
    | '/science'
    | '/search'
    | '/settings'
    | '/technology'
    | '/war'
    | '/world'
    | '/api/crypto-ticker'
    | '/api/editions'
    | '/api/health'
    | '/api/saved'
    | '/api/search'
    | '/api/settings'
    | '/article/$slug'
    | '/editions/$date'
    | '/section/$category'
    | '/api/admin/generate'
    | '/api/admin/rollback'
    | '/api/articles/$id'
    | '/api/edition/latest'
    | '/api/editions/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business'
    | '/crypto'
    | '/culture'
    | '/editions'
    | '/politics'
    | '/pretext-demo'
    | '/saved'
    | '/science'
    | '/search'
    | '/settings'
    | '/technology'
    | '/war'
    | '/world'
    | '/api/crypto-ticker'
    | '/api/editions'
    | '/api/health'
    | '/api/saved'
    | '/api/search'
    | '/api/settings'
    | '/article/$slug'
    | '/editions/$date'
    | '/section/$category'
    | '/api/admin/generate'
    | '/api/admin/rollback'
    | '/api/articles/$id'
    | '/api/edition/latest'
    | '/api/editions/$date'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/crypto'
    | '/culture'
    | '/editions'
    | '/politics'
    | '/pretext-demo'
    | '/saved'
    | '/science'
    | '/search'
    | '/settings'
    | '/technology'
    | '/war'
    | '/world'
    | '/api/crypto-ticker'
    | '/api/editions'
    | '/api/health'
    | '/api/saved'
    | '/api/search'
    | '/api/settings'
    | '/article/$slug'
    | '/editions/$date'
    | '/section/$category'
    | '/api/admin/generate'
    | '/api/admin/rollback'
    | '/api/articles/$id'
    | '/api/edition/latest'
    | '/api/editions/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  CryptoRoute: typeof CryptoRoute
  CultureRoute: typeof CultureRoute
  EditionsRoute: typeof EditionsRouteWithChildren
  PoliticsRoute: typeof PoliticsRoute
  PretextDemoRoute: typeof PretextDemoRoute
  SavedRoute: typeof SavedRoute
  ScienceRoute: typeof ScienceRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TechnologyRoute: typeof TechnologyRoute
  WarRoute: typeof WarRoute
  WorldRoute: typeof WorldRoute
  ApiCryptoTickerRoute: typeof ApiCryptoTickerRoute
  ApiEditionsRoute: typeof ApiEditionsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSavedRoute: typeof ApiSavedRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  SectionCategoryRoute: typeof SectionCategoryRoute
  ApiAdminGenerateRoute: typeof ApiAdminGenerateRoute
  ApiAdminRollbackRoute: typeof ApiAdminRollbackRoute
  ApiArticlesIdRoute: typeof ApiArticlesIdRoute
  ApiEditionLatestRoute: typeof ApiEditionLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/war': {
      id: '/war'
      path: '/war'
      fullPath: '/war'
      preLoaderRoute: typeof WarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pretext-demo': {
      id: '/pretext-demo'
      path: '/pretext-demo'
      fullPath: '/pretext-demo'
      preLoaderRoute: typeof PretextDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politics': {
      id: '/politics'
      path: '/politics'
      fullPath: '/politics'
      preLoaderRoute: typeof PoliticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$category': {
      id: '/section/$category'
      path: '/section/$category'
      fullPath: '/section/$category'
      preLoaderRoute: typeof SectionCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions/$date': {
      id: '/editions/$date'
      path: '/$date'
      fullPath: '/editions/$date'
      preLoaderRoute: typeof EditionsDateRouteImport
      parentRoute: typeof EditionsRoute
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saved': {
      id: '/api/saved'
      path: '/api/saved'
      fullPath: '/api/saved'
      preLoaderRoute: typeof ApiSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/editions': {
      id: '/api/editions'
      path: '/api/editions'
      fullPath: '/api/editions'
      preLoaderRoute: typeof ApiEditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crypto-ticker': {
      id: '/api/crypto-ticker'
      path: '/api/crypto-ticker'
      fullPath: '/api/crypto-ticker'
      preLoaderRoute: typeof ApiCryptoTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/editions/$date': {
      id: '/api/editions/$date'
      path: '/$date'
      fullPath: '/api/editions/$date'
      preLoaderRoute: typeof ApiEditionsDateRouteImport
      parentRoute: typeof ApiEditionsRoute
    }
    '/api/edition/latest': {
      id: '/api/edition/latest'
      path: '/api/edition/latest'
      fullPath: '/api/edition/latest'
      preLoaderRoute: typeof ApiEditionLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/articles/$id': {
      id: '/api/articles/$id'
      path: '/api/articles/$id'
      fullPath: '/api/articles/$id'
      preLoaderRoute: typeof ApiArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/rollback': {
      id: '/api/admin/rollback'
      path: '/api/admin/rollback'
      fullPath: '/api/admin/rollback'
      preLoaderRoute: typeof ApiAdminRollbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/generate': {
      id: '/api/admin/generate'
      path: '/api/admin/generate'
      fullPath: '/api/admin/generate'
      preLoaderRoute: typeof ApiAdminGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EditionsRouteChildren {
  EditionsDateRoute: typeof EditionsDateRoute
}

const EditionsRouteChildren: EditionsRouteChildren = {
  EditionsDateRoute: EditionsDateRoute,
}

const EditionsRouteWithChildren = EditionsRoute._addFileChildren(
  EditionsRouteChildren,
)

interface ApiEditionsRouteChildren {
  ApiEditionsDateRoute: typeof ApiEditionsDateRoute
}

const ApiEditionsRouteChildren: ApiEditionsRouteChildren = {
  ApiEditionsDateRoute: ApiEditionsDateRoute,
}

const ApiEditionsRouteWithChildren = ApiEditionsRoute._addFileChildren(
  ApiEditionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  CryptoRoute: CryptoRoute,
  CultureRoute: CultureRoute,
  EditionsRoute: EditionsRouteWithChildren,
  PoliticsRoute: PoliticsRoute,
  PretextDemoRoute: PretextDemoRoute,
  SavedRoute: SavedRoute,
  ScienceRoute: ScienceRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TechnologyRoute: TechnologyRoute,
  WarRoute: WarRoute,
  WorldRoute: WorldRoute,
  ApiCryptoTickerRoute: ApiCryptoTickerRoute,
  ApiEditionsRoute: ApiEditionsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiSavedRoute: ApiSavedRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  SectionCategoryRoute: SectionCategoryRoute,
  ApiAdminGenerateRoute: ApiAdminGenerateRoute,
  ApiAdminRollbackRoute: ApiAdminRollbackRoute,
  ApiArticlesIdRoute: ApiArticlesIdRoute,
  ApiEditionLatestRoute: ApiEditionLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
